name: 'Issue Tracker'
description: 'Track issue progress and auto-update checkboxes'

inputs:
  issue-number:
    description: 'Issue number to track'
    required: true
  commit-message:
    description: 'Commit message to analyze'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Analyze commit for checkbox patterns
      shell: bash
      run: |
        echo "Analyzing commit message: ${{ inputs.commit-message }}"
        
        # Extract checkbox patterns from commit message
        CHECKBOX_PATTERNS=$(echo "${{ inputs.commit-message }}" | grep -o '\[x\]\|\[ \]' || true)
        
        if [ -n "$CHECKBOX_PATTERNS" ]; then
          echo "Found checkbox patterns: $CHECKBOX_PATTERNS"
          echo "checkbox_patterns=$CHECKBOX_PATTERNS" >> $GITHUB_OUTPUT
        else
          echo "No checkbox patterns found"
          echo "checkbox_patterns=" >> $GITHUB_OUTPUT
        fi
        
    - name: Update issue with progress
      shell: bash
      run: |
        echo "Updating issue #${{ inputs.issue-number }} with progress..."
        
        # This would use GitHub API to update issue
        # For now, we'll log the action
        echo "Would update issue #${{ inputs.issue-number }}"
        
    - name: Check if all checkboxes are completed
      shell: bash
      run: |
        echo "Checking completion status for issue #${{ inputs.issue-number }}..."
        
        # This would check issue body for remaining checkboxes
        # For now, we'll simulate the check
        echo "completion_status=in_progress" >> $GITHUB_OUTPUT 