services:
  apps:
    build: .
    command: pnpm dev:all
    expose:
      - 3000
      - 8005
    volumes:
      - .:/home/app
    ports:
      - 8000:3000
      - 8005:8005
    environment:
      - NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
      - APP_SECRET
      - MONGO_URI

  db_sf:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
      - MONGO_DATA_DIR=/data/db_sf
    expose:
      - 27017
    volumes:
      - db_sf:/data/db_sf

  admin:
    image: mongo-express
    ports:
      - $ADMIN_PORT:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASS
      - ME_CONFIG_MONGODB_URL=$MONGO_URI
      - ME_CONFIG_MONGODB_SERVER=$MONGO_HOST

    depends_on:
      - db_sf

volumes:
  db_sf:
